name:         uniform-fileio
version:      0.0.16
license:      GPL
license-file: GPL_3
maintainer:   Andrew U. Frank <andrewufrank@gmail.com>
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category:     Data Text 
synopsis: uniform file handling operations
description: reduce complexity of Haskell by providing a set of uniformly named
    operations to handle files with an uniform handling of error



extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- monads-tf
# - safe
# - text
# - bytestring
# - pretty-show
# - MissingH
# - split
# - snap-core
# - text-icu
# - network-uri
# - test-invariant
# - numeric-prelude
# - uniform-algebras
#             bytestring -any,
#             directory ,
- directory
#             filepath -any,
#             pureMD5 -any,
#             deepseq,
#             text -any,
#             unix -any,
- unix
#             pipes ,
#             safe,
#             path ,
- path
- path-io
- filepath
#             path-io ,
#             exceptions
#             , split
#             , zlib
- uniform-strings
- uniform-error
- uniform-algebras
# - uniform-time 

library:
  source-dirs: src

# this is only a library, no directly executable
# executables:
#   primo-exe:
#     main:                Testing.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - uniform-algebras

tests:
  strings-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uniform-algebras
    - HTF
    - quickcheck-text
    - uniform-strings
