flags: {}
extra-package-dbs: []
packages:
- .
- ../uniform-strings
- ../uniform-algebras
# - ../uniform-convenience
# - ../uniform-cmdLineArgs
#- ../uniform-fileio
- ../uniform-time
- ../uniform-error
# - ../uniform-json
# - ../uniform-pandoc
# - ../uniform-shake
# - ../uniform-watch
# - ../uniform-webserver
# - ../../fromOthers/bibtex
#- ../../fromOthersInstalled/path
#- ../../fromOthersInstalled/path-io
#- ../../fromOthersInstalled/pretty-show

extra-deps:
- test-invariant-0.4.5.0
#- twitch-0.1.7.2
#- path-0.7.0@sha256:f1629c247f4673650046a690f07958343abc63adc035b451610a550a8ac6055e,3177
#- path-0.6.1@sha256:7a9a56f767a8e47b361af855fea0b4a8d18e7b029734957a65dcd5c0c1abef16,2423

resolver: lts-13.12
