name:         uniform-pandoc 
version:      0.0.2.1
license:      GPL
license-file: GPL_3
maintainer:   Andrew U. Frank <andrewufrank@gmail.com>
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category:     Uniformhandling of   some pandoc stuff
synopsis:   handling of   some pandoc stuff   
description: | 
  remove particular aspects of abstraction 



extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- pandoc

# - uniform

library:
  source-dirs: 
  - .   
# the '.' finds the library in their folders with LibName

tests:
  pandoctest:
    main:                Testing.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uniform 
    - HTF
    - ReplaceUmlaut 