flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- ../uniform-strings
- ../uniform-algebras
# - ../uniform-convenience
# - ../uniform-cmdLineArgs
# - ../uniform-fileio
#- ../uniform-time
- ../uniform-error
# - ../uniform-pretty
# - ../uniform-json
# - ../uniform-pandoc
# - ../uniform-shake
# - ../uniform-watch
# - ../uniform-webserver
# - ../../fromOthers/bibtex
#- ../../fromOthersInstalled/path
#- ../../fromOthersInstalled/path-io
# - ../../fromOthersInstalled/pretty-show

#/home/frank/Workspace8/fromOthersInstalled
#/home/frank/Workspace8/uniform/uniform-algebras

- test-invariant-0.4.5.0
#- twitch-0.1.7.2
#- path-0.7.0
#- path-io-1.6.0
resolver: lts-16.0
