name:         uniform-error
version:      0.0.10.0
license:      GPL
license-file: GPL_3
maintainer:   Andrew U. Frank <andrewufrank@gmail.com>
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category: Error Exception
synopsis: handling of errors in the uniform framework
description: |
  a close to minimal package to handle errors and exception
  in a simple but flexible way to reduce complexity of Haskell.
      
  Please see the README on GitHub at <https://github.com/githubuser/primo#readme>

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

# this is only a library, no directly executable
# executables:
#   primo-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - uniform-algebras

tests:
  error-test:
    main:                TestingError.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # dependencies:
    # - uniform-algebras
    # - HTF
