flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- ../uniform-strings
- ../uniform-algebras
- ../uniform-convenience
- ../uniform-cmdLineArgs
- ../uniform-fileio
- ../uniform-time
- ../uniform-error
- ../uniform-ftp
- ../uniform-http
- ../uniform-json
- ../uniform-pandoc
# - ../uniform-shake
# - ../uniform-watch
- ../uniform-webserver
- ../../fromOthersInstalled/bibtex
# - ../../fromOthers/path
# - ../../fromOthers/path-io
#- ../../fromOthersInstalled/pretty-show

- test-invariant-0.4.5.0
# - twitch-0.1.7.2
- ftphs-1.0.9.2
resolver: lts-17.5
ghc-options:
  "$everything": -haddock
  "$everything": -Wno-deprecations
