flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- ../uniform-strings
- ../uniform-algebras
#- ../uniform-convenience
# - ../uniform-cmdLineArgs
- ../uniform-fileio
- ../uniform-time
- ../uniform-error
- ../uniform-json
# - ../uniform-cers/path-io
#- ../../fromOthersInstalled/pretty-show
# - /home/frank/Workspace8/LitTextWork/TreeTagSets
# - /home/frank/Workspace8/4lit/treetagger

- test-invariant-0.4.5.0
# - twitch-0.1.7.2
resolver: lts-17.5
ghc-options:
  "$everything": -haddock
  "$everything": -Wno-deprecations
