name:         uniform-cmdLineArgs
version:      0.0.1.0
license:      GPL
license-file: GPL_3
maintainer:   Andrew U. Frank <andrewufrank@gmail.com>
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category:     CmdLineArgs
synopsis:     a convenient handling of command line arguments
description: | 
  deals with the command line arguments and fills with decent defaults


extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- monads-tf
- uniformBase
# - safe
# - text
# - bytestring
# # - pretty-show
# # - MissingH
# # - split
# # - snap-core
# # - text-icu
# # - network-uri
# # - test-invariant
# # - numeric-prelude
# # - uniform-algebras
# #             bytestring -any,
# #             directory ,
# - directory
# #             filepath -any,
# #             pureMD5 -any,
# - pureMD5
# - deepseq
# # - text
# #             deepseq,
# #             text -any,
# #             unix -any,
# - unix
# - pipes
# #             pipes ,
# #             safe,
# #             path ,
# - path
# - path-io
# - filepath
# #             path-io ,
# #             exceptions
# - exceptions
# #             , split
# - zlib
- uniform-strings
- uniform-error
- uniform-algebras
# - uniform-convenience
- uniform-fileio
# - uniform-time
# # - uniform-time 
- HTF
- optparse-applicative
# # - test-invariant

library:
  source-dirs: src

# this is only a library, no directly executable
# executables:
#   primo-exe:
#     main:                Testing.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - uniform-algebras

tests:
  strings-test:
    main:                Testing.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uniform-algebras
    - HTF
    - test-invariant
    - quickcheck-text
    - uniform-strings
    - uniform-fileio
    - uniform-cmdLineArgs
