name:         uniform-algebras
version:      0.0.10.0
license:      MIT
maintainer:   Andrew U. Frank <andrewufrank@gmail.com>
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category:     Algebra
synopsis:     some simple algebras, eg. zero
description: |
    simple algebras without much mathematical underpinning
    zero (not a semigroupoid...)
    exports also Maybe and Either
# Please see the README on GitHub at <https://github.com/githubuser/primo#readme>

# verbatim:
#   cabal-version: 3.0

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: 
    - .

# this is only a library, no directly executable

# there are no tests used so far:
# tests:
#   algebra-test:
#     main:                Testing.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - HTF
#     - uniform-algebras
#     - uniform-error
